# Generated by Django 3.0.2 on 2020-02-08 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PWA', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JoinReqeust',
            new_name='TempRegister',
        ),
    ]
